- type: job
  id: SyndAnarchykeeper # Оперативник
  name: job-name-anarchykeeper
  description: job-description-anarchy
  playTimeTracker: JobAnarchykeeperTracker
  requirements:
  startingGear: AnarchykeeperGear
  icon: "JobIconSyndieMarksman"
  supervisors: job-supervisors-anarchykeeper
  access:
  - SyndicateAgent
  - Maintenance
  extendedAccess:
  - NuclearOperative

- type: job
  id: SyndAnarchykeeperCargoTechnician # Логист
  name: job-name-anarchykeeper-cargotechnician
  description: job-description-anarchykeeper-cargotechnician
  playTimeTracker: JobAnarchykeeperCargoTechnicianTracker
  requirements:
  startingGear: SyndieCargotechGear
  icon: "JobIconSyndieScientist"
  supervisors: job-supervisors-anarchykeeper
  access:
  - SyndicateAgent
  - Maintenance
  - Engineering
  - Cargo
  - NuclearOperative

- type: job
  id: SyndAnarchykeeperOfficer # Офицер
  name: job-name-anarchykeeper-officer
  description: job-description-anarchykeeper-officer
  playTimeTracker: JobAnarchykeeperOfficerTracker
  requirements:
  startingGear: AnarchykeeperOfficerGear
  icon: "JobIconMasterAtArms"
  supervisors: job-supervisors-anarchykeeper
  access:
  - SyndicateAgent
  - NuclearOperative
  - Cargo
  - Engineering
  - Medical
