- type: job
  id: SolfedPeacekeeper
  name: job-name-peacekeeper
  description: job-description-peacekeeper
  playTimeTracker: JobPeacekeeperTracker
  requirements:
  - !type:AgeRequirement # Minimum 18
    requiredAge: 18
  - !type:AgeRequirement # Maximum 45
    requiredAge: 45
    inverted: true
  - !type:SpeciesRequirement # Only humans
    species:
    - Human
  startingGear: SolfedPeacekeeperGear
  icon: "JobIconNTSolider"
  supervisors: job-supervisors-peacekeeper
  access:
  - Maintenance
  - Security
  extendedAccess:
  - Command
  - Medical
  - Engineering
  - Cargo
  - Armory

- type: job
  id: SolfedPeacekeeperMedic
  name: job-name-peacekeeper-medic
  description: job-description-peacekeeper-medic
  playTimeTracker: JobPeacekeeperMedicTracker
  requirements:
  - !type:AgeRequirement # Minimum 20
    requiredAge: 20
  - !type:AgeRequirement # Maximum 45
    requiredAge: 45
    inverted: true
  - !type:SpeciesRequirement # Only humans or moths
    species:
    - Human
    - Moth
  startingGear: SolfedPeacekeeperMedicGear
  icon: "JobIconNTParamed"
  supervisors: job-supervisors-peacekeeper
  access:
  - Maintenance
  - Medical
  - Security
  extendedAccess:
  - Command
  - Engineering
  - Cargo

- type: job
  id: SolfedPeacekeeperEngineer
  name: job-name-peacekeeper-engineer
  description: job-description-peacekeeper-engineer
  playTimeTracker: JobPeacekeeperEngineerTracker
  requirements:
  - !type:AgeRequirement # Minimum 20
    requiredAge: 20
  - !type:AgeRequirement # Maximum 45
    requiredAge: 45
    inverted: true
  - !type:SpeciesRequirement # Only humans or reptilians
    species:
    - Human
    - Reptilian
  startingGear: SolfedPeacekeeperEngineerGear
  icon: "JobIconNTEngineer"
  supervisors: job-supervisors-peacekeeper
  access:
  - Maintenance
  - Engineering
  - Security
  extendedAccess:
  - Command
  - Medical
  - Cargo
  - Armory

- type: job
  id: SolfedPeacekeeperCargoTechnician
  name: job-name-peacekeeper-cargotechnician
  description: job-description-peacekeeper-cargotechnician
  playTimeTracker: JobPeacekeeperCargoTechnicianTracker
  requirements:
  - !type:AgeRequirement # Minimum 19
    requiredAge: 19
  - !type:AgeRequirement # Maximum 45
    requiredAge: 50
    inverted: true
  - !type:SpeciesRequirement # Only humans or moths or reptilians
    species:
    - Human
    - Moth
    - Reptilian
  startingGear: SolfedPeacekeeperCargoTechnicianGear
  icon: "JobIconNTLogistics"
  supervisors: job-supervisors-peacekeeper
  access:
  - Cargo
  - Maintenance
  - Security
  - Armory
  extendedAccess:
  - Medical
  - Engineering
  - Command

- type: job
  id: SolfedPeacekeeperOfficer
  name: job-name-peacekeeper-officer
  description: job-description-peacekeeper-officer
  playTimeTracker: JobPeacekeeperOfficerTracker
  requirements:
  - !type:AgeRequirement # Minimum 25
    requiredAge: 25
  - !type:AgeRequirement # Maximum 45
    requiredAge: 50
    inverted: true
  - !type:SpeciesRequirement # Only humans
    species:
    - Human
  startingGear: SolfedPeacekeeperOfficerGear
  icon: "JobIconSolFed"
  supervisors: job-supervisors-peacekeeper-officer
  access:
  - Command
  - Maintenance
  - Medical
  - Engineering
  - Cargo
  - Security
  - Armory
